// Generated by gencpp from file path_collision_check/IsTraValRequest.msg
// DO NOT EDIT!


#ifndef PATH_COLLISION_CHECK_MESSAGE_ISTRAVALREQUEST_H
#define PATH_COLLISION_CHECK_MESSAGE_ISTRAVALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_collision_check
{
template <class ContainerAllocator>
struct IsTraValRequest_
{
  typedef IsTraValRequest_<ContainerAllocator> Type;

  IsTraValRequest_()
    : file_name()  {
    }
  IsTraValRequest_(const ContainerAllocator& _alloc)
    : file_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _file_name_type;
  _file_name_type file_name;





  typedef boost::shared_ptr< ::path_collision_check::IsTraValRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_collision_check::IsTraValRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IsTraValRequest_

typedef ::path_collision_check::IsTraValRequest_<std::allocator<void> > IsTraValRequest;

typedef boost::shared_ptr< ::path_collision_check::IsTraValRequest > IsTraValRequestPtr;
typedef boost::shared_ptr< ::path_collision_check::IsTraValRequest const> IsTraValRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_collision_check::IsTraValRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_collision_check::IsTraValRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_collision_check::IsTraValRequest_<ContainerAllocator1> & lhs, const ::path_collision_check::IsTraValRequest_<ContainerAllocator2> & rhs)
{
  return lhs.file_name == rhs.file_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_collision_check::IsTraValRequest_<ContainerAllocator1> & lhs, const ::path_collision_check::IsTraValRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_collision_check

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::path_collision_check::IsTraValRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_collision_check::IsTraValRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_collision_check::IsTraValRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_collision_check::IsTraValRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_collision_check::IsTraValRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_collision_check::IsTraValRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_collision_check::IsTraValRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2415261c9605b9f38867ffbbe495fc04";
  }

  static const char* value(const ::path_collision_check::IsTraValRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2415261c9605b9f3ULL;
  static const uint64_t static_value2 = 0x8867ffbbe495fc04ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_collision_check::IsTraValRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_collision_check/IsTraValRequest";
  }

  static const char* value(const ::path_collision_check::IsTraValRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_collision_check::IsTraValRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string file_name\n"
;
  }

  static const char* value(const ::path_collision_check::IsTraValRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_collision_check::IsTraValRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.file_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IsTraValRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_collision_check::IsTraValRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_collision_check::IsTraValRequest_<ContainerAllocator>& v)
  {
    s << indent << "file_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.file_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_COLLISION_CHECK_MESSAGE_ISTRAVALREQUEST_H
