// Generated by gencpp from file path_collision_check/IsTraVal.msg
// DO NOT EDIT!


#ifndef PATH_COLLISION_CHECK_MESSAGE_ISTRAVAL_H
#define PATH_COLLISION_CHECK_MESSAGE_ISTRAVAL_H

#include <ros/service_traits.h>


#include <path_collision_check/IsTraValRequest.h>
#include <path_collision_check/IsTraValResponse.h>


namespace path_collision_check
{

struct IsTraVal
{

typedef IsTraValRequest Request;
typedef IsTraValResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsTraVal
} // namespace path_collision_check


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_collision_check::IsTraVal > {
  static const char* value()
  {
    return "33c97e92ddfb5fd9eeda43da1e556307";
  }

  static const char* value(const ::path_collision_check::IsTraVal&) { return value(); }
};

template<>
struct DataType< ::path_collision_check::IsTraVal > {
  static const char* value()
  {
    return "path_collision_check/IsTraVal";
  }

  static const char* value(const ::path_collision_check::IsTraVal&) { return value(); }
};


// service_traits::MD5Sum< ::path_collision_check::IsTraValRequest> should match
// service_traits::MD5Sum< ::path_collision_check::IsTraVal >
template<>
struct MD5Sum< ::path_collision_check::IsTraValRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_collision_check::IsTraVal >::value();
  }
  static const char* value(const ::path_collision_check::IsTraValRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_collision_check::IsTraValRequest> should match
// service_traits::DataType< ::path_collision_check::IsTraVal >
template<>
struct DataType< ::path_collision_check::IsTraValRequest>
{
  static const char* value()
  {
    return DataType< ::path_collision_check::IsTraVal >::value();
  }
  static const char* value(const ::path_collision_check::IsTraValRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_collision_check::IsTraValResponse> should match
// service_traits::MD5Sum< ::path_collision_check::IsTraVal >
template<>
struct MD5Sum< ::path_collision_check::IsTraValResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_collision_check::IsTraVal >::value();
  }
  static const char* value(const ::path_collision_check::IsTraValResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_collision_check::IsTraValResponse> should match
// service_traits::DataType< ::path_collision_check::IsTraVal >
template<>
struct DataType< ::path_collision_check::IsTraValResponse>
{
  static const char* value()
  {
    return DataType< ::path_collision_check::IsTraVal >::value();
  }
  static const char* value(const ::path_collision_check::IsTraValResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_COLLISION_CHECK_MESSAGE_ISTRAVAL_H
