// Generated by gencpp from file path_collision_check/IsTraValResponse.msg
// DO NOT EDIT!


#ifndef PATH_COLLISION_CHECK_MESSAGE_ISTRAVALRESPONSE_H
#define PATH_COLLISION_CHECK_MESSAGE_ISTRAVALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_collision_check
{
template <class ContainerAllocator>
struct IsTraValResponse_
{
  typedef IsTraValResponse_<ContainerAllocator> Type;

  IsTraValResponse_()
    : IsVal(false)  {
    }
  IsTraValResponse_(const ContainerAllocator& _alloc)
    : IsVal(false)  {
  (void)_alloc;
    }



   typedef uint8_t _IsVal_type;
  _IsVal_type IsVal;





  typedef boost::shared_ptr< ::path_collision_check::IsTraValResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_collision_check::IsTraValResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IsTraValResponse_

typedef ::path_collision_check::IsTraValResponse_<std::allocator<void> > IsTraValResponse;

typedef boost::shared_ptr< ::path_collision_check::IsTraValResponse > IsTraValResponsePtr;
typedef boost::shared_ptr< ::path_collision_check::IsTraValResponse const> IsTraValResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_collision_check::IsTraValResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_collision_check::IsTraValResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_collision_check::IsTraValResponse_<ContainerAllocator1> & lhs, const ::path_collision_check::IsTraValResponse_<ContainerAllocator2> & rhs)
{
  return lhs.IsVal == rhs.IsVal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_collision_check::IsTraValResponse_<ContainerAllocator1> & lhs, const ::path_collision_check::IsTraValResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_collision_check

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::path_collision_check::IsTraValResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_collision_check::IsTraValResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_collision_check::IsTraValResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_collision_check::IsTraValResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_collision_check::IsTraValResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_collision_check::IsTraValResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_collision_check::IsTraValResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "969c9f71a064c9fd7b7dd8d05e9cc517";
  }

  static const char* value(const ::path_collision_check::IsTraValResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x969c9f71a064c9fdULL;
  static const uint64_t static_value2 = 0x7b7dd8d05e9cc517ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_collision_check::IsTraValResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_collision_check/IsTraValResponse";
  }

  static const char* value(const ::path_collision_check::IsTraValResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_collision_check::IsTraValResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool IsVal\n"
"\n"
;
  }

  static const char* value(const ::path_collision_check::IsTraValResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_collision_check::IsTraValResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.IsVal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IsTraValResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_collision_check::IsTraValResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_collision_check::IsTraValResponse_<ContainerAllocator>& v)
  {
    s << indent << "IsVal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.IsVal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_COLLISION_CHECK_MESSAGE_ISTRAVALRESPONSE_H
